# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: '顿玄的个人博客'
    # twitter: 'GetResearchDev'
  analytics:
    google_analytics: 'G-98ELQLG275'
    # google_tag_manager: 'GTM-5X9C8DCV'
    microsoft_clarity: 'h03ochyksg'
    # baidu_tongji: 'bb7272f7f9bc6a034eacf48ee04d15d4'
    # plausible: ''
    # fathom: ''
    # pirsch: ''
  # verification:
  #   google: ''
  #   baidu: ''

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© 2022 - {year} 顿玄。 本网站遵循 {license} 协议'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2006-01-02'
  time_format: '15:04'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/dunxuan/dunxuan.github.io'
    content_dir: content
    branch: main
  comment:
    provider: 'giscus'
    giscus:
      repo: 'dunxuan/dunxuan.github.io'
      repo_id: 'R_kgDOK1fEcg'
      category: 'Announcements'
      category_id: 'DIC_kwDOK1fEcs4Cbe0U'
      theme: preferred_color_scheme
      language_code: zh-CN
      mapping: pathname