# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: forest
  theme_night: forest
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: '顿玄的博客'
  analytics:
    google_analytics: 'G-98ELQLG275'
    microsoft_clarity: 'h03ochyksg'
    baidu_tongji: 'bb7272f7f9bc6a034eacf48ee04d15d4'
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: c
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© 2022 - {year} 顿玄. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/dunxuan/dunxuan.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
